/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package besokminggu.algeotubes;

import static besokminggu.algeotubes.InputMatriksKeyboard.closeAllWindows;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import besokminggu.Fungsi.TextToMatriks;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author DELL
 */
public class Input extends javax.swing.JFrame {

    /**
     * Creates new form Input
     */
    public Input() {
        initComponents();
        if (AlgeoTubes.ImplementasiInterpolasiBicubicSpline == 1){
            jPanel2.setVisible(false);
        }
    }
    public int getM(){
        try {
            int number = Integer.parseInt(jTextField2.getText());
            return number;
        } catch (NumberFormatException e) {
            return -1;
         }
    }
    public int getN(){
        try {
            int number = Integer.parseInt(jTextField1.getText());
            return number;
        } catch (NumberFormatException e) {
            return -1;
         }
    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton1.setText("File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("No file choosed");

        jButton3.setText("Import File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("X");

        jButton2.setText("Keyboard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Pilih Input");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    int returnVal = 1;
    File selectedFile;
    String filename;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser j = new JFileChooser();
        if (AlgeoTubes.ImplementasiInterpolasiBicubicSpline == 1 ){
            FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
            j.setFileFilter(filter);
        } else {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("TXT Files", "txt");
            j.setFileFilter(filter);
        }
        
        returnVal = j.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            selectedFile = j.getSelectedFile();
            filename = selectedFile.getAbsolutePath();
            jLabel2.setText(filename);
        }
        // Open the save dialog
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AlgeoTubes.matriksinput = TextToMatriks.readMatrixFromFile(filename);
        if (returnVal == JFileChooser.APPROVE_OPTION && (AlgeoTubes.InterpolasiBicubicSpline == 1 || AlgeoTubes.InterpolasiPolinom == 1)) {
            if (AlgeoTubes.matriksinput[0][0] == 109105110103103117.0){
                JOptionPane.showMessageDialog(null, "Matrix Input not true. Contact Ojan for help. Code error = 5", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                double[][] tempmat = new double[AlgeoTubes.matriksinput.length-1][AlgeoTubes.matriksinput[0].length];
                AlgeoTubes.x = AlgeoTubes.matriksinput[AlgeoTubes.matriksinput.length-1][0];
                AlgeoTubes.y = AlgeoTubes.matriksinput[AlgeoTubes.matriksinput.length-1][1];
                
                for (int i=0;i<AlgeoTubes.matriksinput.length-1;i++){
                    for (int j=0;j<AlgeoTubes.matriksinput[0].length;j++){
                        tempmat[i][j] = AlgeoTubes.matriksinput[i][j];
                    }
                }
                AlgeoTubes.matriksinput = new double[tempmat.length][tempmat[0].length];
                for (int i=0;i<tempmat.length;i++){
                    for (int j=0;j<tempmat[0].length;j++){
                        AlgeoTubes.matriksinput[i][j] = tempmat[i][j];
                    }
                }
                System.out.println(AlgeoTubes.x);
                try {
                    afterInput(false, false, false);
                } catch (IOException ex) {
                    Logger.getLogger(Input.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if (returnVal == JFileChooser.APPROVE_OPTION && AlgeoTubes.ImplementasiInterpolasiBicubicSpline != 1) {
            if (AlgeoTubes.matriksinput[0][0] == 109105110103103117.0){
                JOptionPane.showMessageDialog(null, "Matrix Input not true. Contact Ojan for help. Code error = 5", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (AlgeoTubes.matriksinput[0][0] == 109105110103103117.1){
                JOptionPane.showMessageDialog(null, "Matrix Input not true. Contact Ojan for help. Code error = 5", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                boolean square = AlgeoTubes.matriksinput.length == AlgeoTubes.matriksinput[0].length;
                boolean under_3 = AlgeoTubes.matriksinput.length < 3 && AlgeoTubes.matriksinput[0].length < 3;
                boolean inverse_spl = AlgeoTubes.matriksinput.length == AlgeoTubes.matriksinput[0].length-1;
                try {
                    afterInput(square, under_3,inverse_spl);
                } catch (IOException ex) {
                    Logger.getLogger(Input.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if (returnVal == JFileChooser.APPROVE_OPTION){
            AlgeoTubes.x = SpecialInput.getx();
            AlgeoTubes.pathfile = filename;
            try {
                afterInput(false, false, false);
            } catch (IOException ex) {
                Logger.getLogger(Input.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (returnVal != JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(null, "No file detected. Contact Ojan for help. Code error = 4", "Error, input ulang path!", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "OOPS! Contact Ojan for help. Code error = :P", "Bukan error kok", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void afterInput(boolean determinan, boolean under_3, boolean inverse_spl) throws IOException{
        if (AlgeoTubes.SPLEliminasiGauss == 1) {
            new SPLMetodeEliminasiGauss().setVisible(true);

        } else if (AlgeoTubes.SPLELiminasiGaussJordan == 1){
            new SPLMetodeEliminasiGaussJordan().setVisible(true);

        } else if (AlgeoTubes.SPLMatriksBalikan == 1 && inverse_spl){
            new SPLMetodeMatriksBalikan().setVisible(true);

        } else if (AlgeoTubes.SPLCramer == 1 && inverse_spl){
            new SPLKaidahCramer().setVisible(true);

        } else if (AlgeoTubes.DETDeterminanNxN == 1 && determinan && under_3){
            new DETDeterminanNxN().setVisible(true);

        } else if (AlgeoTubes.DETDeterminanNxN == 1 && determinan && !under_3){
            JOptionPane.showMessageDialog(null, "You found easter egg WOW! Your matrix is bigger than 3 id*o*.", "Maap ga maap kasar dikit.", JOptionPane.ERROR_MESSAGE);

        } else if (AlgeoTubes.DETDeterminandenganKofaktor == 1 && determinan){
            new DETDeterminandenganKofaktor().setVisible(true);

        } else if (AlgeoTubes.DETDeterminanMatriksSegitiga == 1 && determinan){
            new DETDeterminanMatriksSegitiga().setVisible(true);

        } else if (AlgeoTubes.INVAdjoin == 1 && determinan){
            new INVMatriksinversedenganAdjoin().setVisible(true);

        } else if (AlgeoTubes.INVBalikan == 1 && determinan){
            new INVMetodematriksBalikan().setVisible(true);

        } else if (AlgeoTubes.InterpolasiPolinom == 1){
            new InterpolasiPolinom().setVisible(true);

        } else if (AlgeoTubes.InterpolasiBicubicSpline == 1){
            new InterpolasiBicubicSpline().setVisible(true);

        } else if (AlgeoTubes.RegresiLinearBerganda == 1){
            new RegresiLinierBerganda().setVisible(true);

        } else if (AlgeoTubes.ImplementasiInterpolasiBicubicSpline == 1){
            new ImplementasiBicubicSpline().setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(null, "An error occurred. Contact Ojan for help. Code error = 1", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    public static void ResetState(){
        AlgeoTubes.SPLEliminasiGauss = 0;
        AlgeoTubes.SPLELiminasiGaussJordan = 0;
        AlgeoTubes.SPLMatriksBalikan = 0;
        AlgeoTubes.SPLCramer = 0;
        AlgeoTubes.DETDeterminanNxN = 0;
        AlgeoTubes.DETDeterminandenganKofaktor = 0;
        AlgeoTubes.DETDeterminanMatriksSegitiga = 0;
        AlgeoTubes.INVAdjoin = 0;
        AlgeoTubes.INVBalikan = 0;
        AlgeoTubes.InterpolasiPolinom = 0;
        AlgeoTubes.InterpolasiBicubicSpline = 0;
        AlgeoTubes.RegresiLinearBerganda = 0;
        AlgeoTubes.ImplementasiInterpolasiBicubicSpline = 0;
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ResetState();
        closeAllWindows();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AlgeoTubes.n = getN();
        AlgeoTubes.m = getM();
        if (AlgeoTubes.n <= 0 || AlgeoTubes.m<=0) {
            JOptionPane.showMessageDialog(null, "Uh-oh! Inputnya error mas/mba! Error code = 2", "Error Ngabs Besar Array", JOptionPane.ERROR_MESSAGE);
        } else if (AlgeoTubes.n != AlgeoTubes.m && (AlgeoTubes.DETDeterminanNxN == 1 || AlgeoTubes.DETDeterminandenganKofaktor == 1 || AlgeoTubes.DETDeterminanMatriksSegitiga == 1 || AlgeoTubes.INVAdjoin == 1 || AlgeoTubes.INVBalikan == 1)){
            JOptionPane.showMessageDialog(null, "Uh-oh! Inputnya error mas/mba! Error code = 3", "Error Ngabs Kayaknya Harus NxN", JOptionPane.ERROR_MESSAGE);
        } else if (AlgeoTubes.n > 3 && AlgeoTubes.m > 3  && AlgeoTubes.DETDeterminanNxN == 1) {
            JOptionPane.showMessageDialog(null, "Uh-oh! Inputnya error mas/mba! Error code = 4", "Error Ngabs Kayaknya Harus Kurang dari 3 lebih dari 0", JOptionPane.ERROR_MESSAGE);
        } else {
            close();
            if(AlgeoTubes.InterpolasiPolinom == 1 || AlgeoTubes.InterpolasiBicubicSpline == 1 || AlgeoTubes.ImplementasiInterpolasiBicubicSpline == 1){
                new SpecialInput().setVisible(true);
            }
            new InputMatriksKeyboard().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
